services:
  postgres:
    image: postgres:15
    volumes:
      - /mnt/superlarsen/libretime/postgres:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U libretime

  rabbitmq:
    image: rabbitmq:3.13-alpine
    healthcheck:
      test: nc -z 127.0.0.1 5672

  playout:
    image: ghcr.io/libretime/libretime-playout:${LIBRETIME_VERSION:-latest}
    init: true
    ulimits:
      nofile: 1024
    depends_on:
      - rabbitmq
    volumes:
      - ${LIBRETIME_CONFIG_FILEPATH:-./config.yml}:/etc/libretime/config.yml:ro
      - /mnt/superlarsen/libretime/playout:/app
    environment:
      LIBRETIME_GENERAL_PUBLIC_URL: http://nginx:8080
    networks:
      - default
      - smtp

  liquidsoap:
    image: ghcr.io/libretime/libretime-playout:${LIBRETIME_VERSION:-latest}
    command: /usr/local/bin/libretime-liquidsoap
    init: true
    ulimits:
      nofile: 1024
    ports:
      - 8001:8001
      - 8002:8002
    depends_on:
      - rabbitmq
    volumes:
      - ${LIBRETIME_CONFIG_FILEPATH:-./config.yml}:/etc/libretime/config.yml:ro
      - /mnt/superlarsen/libretime/playout:/app
    environment:
      LIBRETIME_GENERAL_PUBLIC_URL: http://nginx:8080
    networks:
      - default

  analyzer:
    image: ghcr.io/libretime/libretime-analyzer:${LIBRETIME_VERSION:-latest}
    init: true
    ulimits:
      nofile: 1024
    depends_on:
      - rabbitmq
    volumes:
      - ${LIBRETIME_CONFIG_FILEPATH:-./config.yml}:/etc/libretime/config.yml:ro
      - /mnt/superlarsen/libretime/storage:/srv/libretime
    environment:
      LIBRETIME_GENERAL_PUBLIC_URL: http://nginx:8080

  worker:
    image: ghcr.io/libretime/libretime-worker:${LIBRETIME_VERSION:-latest}
    init: true
    ulimits:
      nofile: 1024
    depends_on:
      - rabbitmq
    volumes:
      - ${LIBRETIME_CONFIG_FILEPATH:-./config.yml}:/etc/libretime/config.yml:ro
    environment:
      LIBRETIME_GENERAL_PUBLIC_URL: http://nginx:8080
    networks:
      - default
      - smtp

  api:
    image: ghcr.io/libretime/libretime-api:${LIBRETIME_VERSION:-latest}
    init: true
    ulimits:
      nofile: 1024
    depends_on:
      - postgres
      - rabbitmq
    volumes:
      - ${LIBRETIME_CONFIG_FILEPATH:-./config.yml}:/etc/libretime/config.yml:ro
      - /mnt/superlarsen/libretime/storage:/srv/libretime
    networks:
      - default
      - smtp

  legacy:
    image: ghcr.io/libretime/libretime-legacy:${LIBRETIME_VERSION:-latest}
    init: true
    ulimits:
      nofile: 1024
    depends_on:
      - postgres
      - rabbitmq
    volumes:
      - ${LIBRETIME_CONFIG_FILEPATH:-./config.yml}:/etc/libretime/config.yml:ro
      - /mnt/superlarsen/libretime/storage:/srv/libretime
    networks:
      - default
      - smtp

  nginx:
    image: ghcr.io/libretime/libretime-nginx:${LIBRETIME_VERSION:-latest}
    depends_on:
      - legacy
    volumes:
      - /mnt/superlarsen/libretime/storage:/srv/libretime:ro
    networks:
      - caddy
      - default
    labels:
      caddy: libretime.superlarsen.fr
      caddy.reverse_proxy: "{{upstreams 8080}}"

  icecast:
    image: ghcr.io/libretime/icecast:2.4.4
    networks:
      - caddy
      - default
    labels:
      caddy: icecast.superlarsen.fr
      caddy.reverse_proxy: "{{upstreams 8000}}"

networks:
  caddy:
    external: true
  smtp:
    external: true