[[stack]]
name = "superlarsen-castopod"
tags = ["superlarsen"]
[stack.config]
server = "cartons"
links = [
  "https://castopod.superlarsen.fr"
]
linked_repo = "superlarsen-main"
run_directory = "stacks/castopod"
environment = """
MYSQL_DATABASE=castopod
MYSQL_USER=castopod
MYSQL_PASSWORD=[[SUPERLARSEN_CASTOPOD_MYSQL_PASSWORD]]
CP_BASEURL=https://castopod.superlarsen.fr
CP_CACHE_HANDLER=redis
CP_REDIS_HOST=redis
CP_REDIS_PASSWORD=[[SUPERLARSEN_CASTOPOD_CP_REDIS_PASSWORD]]
CP_ANALYTICS_SALT=[[SUPERLARSEN_CASTOPOD_CP_ANALYTICS_SALT]]
MYSQL_ROOT_PASSWORD=[[SUPERLARSEN_CASTOPOD_MYSQL_ROOT_PASSWORD]]
CP_DISABLE_HTTPS=0
CP_EMAIL_FROM=castopod@superlarsen.fr
CP_EMAIL_SMTP_HOST=smtp.gmail.com
CP_EMAIL_SMTP_USERNAME=[[SUPERLARSEN_SMTP_USER]]
CP_EMAIL_SMTP_PASSWORD=[[SUPERLARSEN_SMTP_PASSWORD]]
CP_EMAIL_SMTP_PORT=587
CP_EMAIL_SMTP_CRYPTO=tls
"""

##

[[stack]]
name = "superlarsen-libretime"
tags = ["superlarsen"]
[stack.config]
server = "cartons"
links = [
  "https://libretime.superlarsen.fr"
]
linked_repo = "superlarsen-main"
webhook_force_deploy = true
run_directory = "stacks/libretime"
pre_deploy.command = """
/bin/bash -a -c "apt update && apt install -y gettext && source ./.env; envsubst < config.template.yml > config.yml"
docker compose -p superlarsen-libretime -f compose.yaml run --rm api libretime-api migrate
"""
environment = """
# Libretime
LIBRETIME_VERSION=4.5.0

# Postgres
POSTGRES_PASSWORD=[[SUPERLARSEN_LIBRETIME_POSTGRES_PASSWORD]]
POSTGRES_USER=libretime

# RabbitMQ
RABBITMQ_DEFAULT_PASS=[[SUPERLARSEN_LIBRETIME_RABBITMQ_DEFAULT_PASS]]
RABBITMQ_DEFAULT_VHOST=/libretime
RABBITMQ_DEFAULT_USER=libretime

# Icecast
ICECAST_SOURCE_PASSWORD=[[SUPERLARSEN_LIBRETIME_ICECAST_SOURCE_PASSWORD]]
ICECAST_ADMIN_PASSWORD=[[SUPERLARSEN_LIBRETIME_ICECAST_ADMIN_PASSWORD]]
ICECAST_RELAY_PASSWORD=[[SUPERLARSEN_LIBRETIME_ICECAST_RELAY_PASSWORD]]

# Django
API_KEY=[[SUPERLARSEN_LIBRETIME_API_KEY]]
DJANGO_SECRET_KEY=[[SUPERLARSEN_LIBRETIME_DJANGO_SECRET_KEY]]
PUBLIC_URL=https://libretime.superlarsen.fr

# SMTP
SMTP_USER=[[SUPERLARSEN_SMTP_USER]]
SMTP_PASSWORD=[[SUPERLARSEN_SMTP_PASSWORD]]
"""

##

[[stack]]
name = "superlarsen-wordpress"
tags = ["superlarsen"]
[stack.config]
server = "cartons"
links = ["https://www.superlarsen.fr"]
linked_repo = "superlarsen-main"
run_directory = "stacks/wordpress"
environment = """
WORDPRESS_DB_USER=superlarsen
WORDPRESS_DB_PASSWORD=[[SUPERLARSEN_WORDPRESS_WORDPRESS_DB_PASSWORD]]
WORDPRESS_DB_NAME=superlarsen
MYSQL_DATABASE=superlarsen
MYSQL_USER=superlarsen
MYSQL_PASSWORD=[[SUPERLARSEN_WORDPRESS_WORDPRESS_DB_PASSWORD]]
"""

##

[[repo]]
name = "superlarsen-main"
tags = ["superlarsen"]
[repo.config]
server = "cartons"
builder = "local"
git_account = "trivoallan"
repo = "constructions-incongrues/superlarsen"

##

[[resource_sync]]
name = "superlarsen"
tags = ["superlarsen"]
[resource_sync.config]
linked_repo = "superlarsen-main"
resource_path = [
  "infrastructure/resources.toml",
  "stacks"
]
managed = true
match_tags = ["superlarsen"]